import exist					from './lib_dev/exist';
import isEqual					from './lib_dev/isEqual';
import isEqualNonStrict			from './lib_dev/isEqualNonStrict';
import isFalse					from './lib_dev/isFalse';
import isInstanceOf				from './lib_dev/isInstanceOf';
import isLikeStructure			from './lib_dev/isLikeStructure';
import isNaN					from './lib_dev/isNaN';
import isNill					from './lib_dev/isNill';
import isNotNaN				from './lib_dev/isNotNaN';
import isNotNill				from './lib_dev/isNotNill';
import isNotNull				from './lib_dev/isNotNull';
import isNull					from './lib_dev/isNull';
import isSameNotOrderedStructure	from './lib_dev/isSameNotOrderedStructure';
import isSameStructure			from './lib_dev/isSameStructure';
import isTrue					from './lib_dev/isTrue';
import isTypeOf				from './lib_dev/isTypeOf';
import notExist				from './lib_dev/notExist';

exist.drawResult();
isEqual.drawResult();
isEqualNonStrict.drawResult();
isFalse.drawResult();
isInstanceOf.drawResult();
isLikeStructure.drawResult();
isNaN.drawResult();
isNill.drawResult();
isNotNaN.drawResult();
isNotNill.drawResult();
isNotNull.drawResult();
isNull.drawResult();
isSameNotOrderedStructure.drawResult();
isSameStructure.drawResult();
isTrue.drawResult();
isTypeOf.drawResult();
notExist.drawResult();
